services:
  quanly-pk-fe-service:
    image: quanly-pk-fe-service:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:9004/api/v1}
    container_name: quanly-pk-fe-service
    ports:
      - "${FE_PORT}:80"
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      HTTPS_METHOD: ${HTTPS_METHOD:-noredirect}
    networks:
      - gasy-network

networks:
  gasy-network:
    name: gasy-network
    external: true
